services:
  api:
    build: .
    container_name: main-api
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - MONGO_URI_DOCKER=${MONGO_URI_DOCKER}
      - IS_DOCKER=${IS_DOCKER}
      - SECRET_KEY=${SECRET_KEY}
    restart: "no"
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: "no"

volumes:
  mongo-data:
